import fs from 'fs';
const f = 'D:/닼웤롴덬/digimon-sim/src/effects.js';
let s = fs.readFileSync(f, 'utf8');
const a = "label: `이 턴 종료 시 메모리 -${instr.n}` });";
const a2 = "label: `이 턴 종료 시 메모리 -${instr.n}`, desc: { kind: 'memory', player: ctx.self, n: instr.n } });";
const b = "fn: () => { runScript(instr.then, c2).catch(() => {}); } });";
const b2 = "desc: { kind: 'script', then: instr.then, player: ctx.self, cardId: ctx.sourceCardId, stackUid: ctx.sourceStackUid }, fn: () => { runScript(instr.then, c2).catch(() => {}); } });";
if (s.split(a).length !== 2 || s.split(b).length !== 2) throw new Error('nomatch');
s = s.replace(a, () => a2).replace(b, () => b2);
fs.writeFileSync(f, s);
